'use strict';
// The twelve resorts. Lift endpoints are given in normalised coordinates
// (x: 0..1 across, z: 0 = summit edge .. 1 = valley). Pistes connect a lift's
// top station to a lift's bottom station: [fromLift, toLift].
(function (GS) {
  const ALPINE = { pine: ['#1f5a44', '#24694c', '#2c7a56', '#1a4d3b'], trees: { pine: 3, spruce: 2 } };

  const MOUNTAINS = [
    {
      id: 'sonnalm', seed: 1101, W: 1024, L: 1792, unlock: 0,
      name: 'Sonnalm', region: { de: 'Tirol · Alpen', en: 'Tyrol · Alps' },
      desc: { de: 'Sonnige Einsteiger-Alm mit Übungslift, Hütten und dem ersten Funpark.', en: 'A sunny beginner resort with a practice lift, cosy huts and your first fun park.' },
      hour: 10, weather: 'clear', music: 'alps', diff: 1,
      theme: Object.assign({ rock: '#6e737b', rock2: '#8a8f96', treeDensity: 0.55, treeline: 0.18, rocks: 0.25, deco: 'alpine', palette: ['#ffd36e', '#7fc8ff', '#2f6feb'] }, ALPINE),
      gen: { slopes: [0.55, 0.44, 0.36, 0.3, 0.22, 0.12, 0.04], big: 34, mid: 5, small: 0.7, ridge: 16, bowl: 30, cliffs: 2, cliffDrop: 7 },
      lifts: [
        { type: 'chair', b: [0.5, 0.93], t: [0.47, 0.5], color: '#e63946', name: 'Sonnenbahn' },
        { type: 'tbar', b: [0.27, 0.935], t: [0.24, 0.72], color: '#ffb703', name: 'Zwergerl-Lift' },
        { type: 'chair', b: [0.63, 0.62], t: [0.72, 0.17], color: '#2a9d8f', name: 'Gamsbahn', cost: 4 },
        { type: 'gondola', b: [0.36, 0.56], t: [0.4, 0.07], color: '#2f6feb', name: 'Gipfelbahn', cost: 9 },
      ],
      pistes: [[0, 0], [0, 1], [1, 1], [2, 0], [2, 2], [3, 3], [3, 0], [3, 2]],
      park: 0, paraglide: true, zip: 1,
      challenges: ['slalom', 'collect', 'giant', 'bigair', 'freestyle', 'race', 'downhill', 'treetap', 'slopestyle', 'speed', 'superg', 'freeride', 'paraglide', 'airtime', 'night', 'duel'],
    },
    {
      id: 'tannenwald', seed: 2202, W: 1024, L: 2048, unlock: 6,
      name: 'Tannenwald', region: { de: 'Schwarzwald', en: 'Black Forest' },
      desc: { de: 'Dichte Wälder, verschlungene Waldabfahrten und Baum-Tap-Wettbewerbe.', en: 'Dense forests, winding tree runs and tree-tap contests.' },
      hour: 12, weather: 'cloudy', music: 'forest', diff: 1,
      theme: { pine: ['#1b4f3c', '#22604a', '#2a6e52', '#173f31'], trees: { pine: 2, spruce: 3, birch: 1 }, rock: '#6a6f73', treeDensity: 0.82, treeline: 0.06, rocks: 0.15, deco: 'alpine', palette: ['#2a6e52', '#a7d3a6', '#1b4f3c'] },
      gen: { slopes: [0.45, 0.38, 0.33, 0.28, 0.22, 0.14, 0.04], big: 28, mid: 7, small: 0.9, ridge: 10, bowl: 35, cliffs: 1, cliffDrop: 6 },
      lifts: [
        { type: 'chair', b: [0.45, 0.93], t: [0.4, 0.52], color: '#2a9d8f', name: 'Waldbahn' },
        { type: 'chair', b: [0.66, 0.94], t: [0.7, 0.5], color: '#e76f51', name: 'Fuchsbau' },
        { type: 'chair', b: [0.37, 0.57], t: [0.3, 0.12], color: '#264653', name: 'Hirschsprung', cost: 4 },
        { type: 'gondola', b: [0.7, 0.55], t: [0.62, 0.08], color: '#e9c46a', name: 'Kammbahn', cost: 8 },
      ],
      pistes: [[0, 0], [0, 1], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 1, paraglide: false, zip: 2,
      challenges: ['treetap', 'slalom', 'collect', 'freeride', 'treetap', 'race', 'giant', 'downhill', 'freestyle', 'bigair', 'collect', 'superg', 'avalanche', 'slopestyle', 'duel', 'fog'],
    },
    {
      id: 'gletscher', seed: 3303, W: 1152, L: 2304, unlock: 14,
      name: 'Gletscherspitz', region: { de: 'Wallis · Schweiz', en: 'Valais · Switzerland' },
      desc: { de: 'Hochalpines Gletschergebiet mit blankem Eis, Séracs und gewaltigen Felsbändern.', en: 'High-alpine glacier with blue ice, seracs and huge rock bands.' },
      hour: 14, weather: 'clear', music: 'glacier', diff: 2,
      theme: Object.assign({ rock: '#5d636c', rock2: '#7b828c', treeDensity: 0.32, treeline: 0.62, rocks: 0.5, seracs: 0.4, deco: 'alpine', ice: '#8fcdf0', palette: ['#8fcdf0', '#d9f1ff', '#3a6ea5'] }, ALPINE),
      gen: { slopes: [0.72, 0.58, 0.45, 0.36, 0.3, 0.2, 0.05], big: 48, mid: 7, small: 0.8, ridge: 30, bowl: 26, cliffs: 4, cliffDrop: 11, ice: 1 },
      lifts: [
        { type: 'gondola', b: [0.5, 0.94], t: [0.46, 0.6], color: '#d62828', name: 'Gletscherexpress' },
        { type: 'chair', b: [0.3, 0.66], t: [0.26, 0.3], color: '#003049', name: 'Eisfall', cost: 4 },
        { type: 'chair', b: [0.62, 0.64], t: [0.72, 0.26], color: '#f77f00', name: 'Séracbahn', cost: 7 },
        { type: 'tbar', b: [0.45, 0.32], t: [0.48, 0.07], color: '#fcbf49', name: 'Firnlift', cost: 11 },
      ],
      pistes: [[0, 0], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 0, paraglide: true, zip: 1,
      challenges: ['downhill', 'slalom', 'speed', 'giant', 'freeride', 'collect', 'race', 'airtime', 'superg', 'bigair', 'avalanche', 'paraglide', 'precision', 'freestyle', 'duel', 'speed'],
    },
    {
      id: 'nordlicht', seed: 4404, W: 1024, L: 1920, unlock: 24,
      name: 'Nordlichtfjell', region: { de: 'Lappland · Norwegen', en: 'Lapland · Norway' },
      desc: { de: 'Ewige Nacht, flutlichtbeleuchtete Pisten und tanzende Polarlichter.', en: 'Endless night, floodlit pistes and dancing northern lights.' },
      hour: 22, weather: 'clear', music: 'nordic', diff: 2, lamps: true,
      theme: { pine: ['#173f37', '#1d4d42', '#235a4c'], trees: { spruce: 3, birch: 2 }, rock: '#4f5560', treeDensity: 0.6, treeline: 0.3, rocks: 0.2, deco: 'nordic', aurora: true, tint: '#3a8f7a', tintAmt: 0.08, palette: ['#3ff2a5', '#7c5cff', '#0e1a33'] },
      gen: { slopes: [0.4, 0.34, 0.3, 0.26, 0.2, 0.12, 0.03], big: 26, mid: 6, small: 0.6, ridge: 12, bowl: 40, cliffs: 2, cliffDrop: 8 },
      lifts: [
        { type: 'chair', b: [0.5, 0.94], t: [0.55, 0.52], color: '#3a86ff', name: 'Aurora' },
        { type: 'tbar', b: [0.3, 0.9], t: [0.25, 0.58], color: '#ffbe0b', name: 'Rentier' },
        { type: 'chair', b: [0.6, 0.56], t: [0.68, 0.12], color: '#8338ec', name: 'Polarstern', cost: 4 },
        { type: 'chair', b: [0.32, 0.58], t: [0.36, 0.1], color: '#ff006e', name: 'Mitternacht', cost: 8 },
      ],
      pistes: [[0, 0], [0, 1], [1, 1], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 0, paraglide: false, zip: 2,
      challenges: ['night', 'collect', 'slalom', 'race', 'treetap', 'freestyle', 'giant', 'bigair', 'downhill', 'slopestyle', 'collect', 'superg', 'speed', 'freeride', 'duel'],
    },
    {
      id: 'yukiyama', seed: 5505, W: 1088, L: 2048, unlock: 36,
      name: 'Yukiyama', region: { de: 'Hokkaido · Japan', en: 'Hokkaido · Japan' },
      desc: { de: 'Tiefster Pulverschnee, Schneemonster-Bäume, Torii-Tore und Steinlaternen.', en: 'Bottomless powder, snow-monster trees, torii gates and stone lanterns.' },
      hour: 15, weather: 'snow', music: 'japan', diff: 2, lamps: true,
      theme: { pine: ['#28503f', '#2f5d49', '#244839'], trees: { juhyo: 3, pine: 1, spruce: 1 }, rock: '#5e6168', treeDensity: 0.58, treeline: 0.2, rocks: 0.2, deco: 'japan', palette: ['#ff8fab', '#ffe5ec', '#c8372d'] },
      gen: { slopes: [0.55, 0.45, 0.38, 0.32, 0.24, 0.14, 0.04], big: 36, mid: 8, small: 1.1, ridge: 18, bowl: 30, cliffs: 3, cliffDrop: 8, deep: true },
      lifts: [
        { type: 'gondola', b: [0.48, 0.94], t: [0.5, 0.56], color: '#c8372d', name: 'Sakura-Gondel' },
        { type: 'chair', b: [0.3, 0.6], t: [0.26, 0.16], color: '#2b2d42', name: 'Kitsune', cost: 4 },
        { type: 'chair', b: [0.66, 0.62], t: [0.73, 0.2], color: '#ef233c', name: 'Tanuki', cost: 7 },
        { type: 'chair', b: [0.5, 0.36], t: [0.52, 0.07], color: '#8d99ae', name: 'Fuji-Blick', cost: 11 },
      ],
      pistes: [[0, 0], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 0, paraglide: true, zip: 1,
      challenges: ['freeride', 'treetap', 'slalom', 'collect', 'freeride', 'bigair', 'race', 'giant', 'freestyle', 'avalanche', 'airtime', 'downhill', 'slopestyle', 'paraglide', 'night', 'duel'],
    },
    {
      id: 'vulkan', seed: 6606, W: 1088, L: 2176, unlock: 50,
      name: 'Vulkan Ignis', region: { de: 'Kamtschatka', en: 'Kamchatka' },
      desc: { de: 'Schwarzer Fels, dampfende Fumarolen und ein Krater am Gipfel.', en: 'Black rock, steaming fumaroles and a crater at the summit.' },
      hour: 16, weather: 'cloudy', music: 'volcano', diff: 3, vents: true,
      theme: { trees: { dead: 3, pine: 1 }, pine: ['#2b4a3c', '#334f3f'], rock: '#2b2827', rock2: '#3d3634', treeDensity: 0.28, treeline: 0.5, rocks: 0.6, deco: 'volcano', tint: '#ff7b47', tintAmt: 0.12, snow: '#eef0f3', palette: ['#ff5400', '#ffbd00', '#2b2827'] },
      gen: { slopes: [0.15, 0.62, 0.55, 0.42, 0.32, 0.18, 0.05], big: 40, mid: 7, small: 1, ridge: 34, bowl: 20, cliffs: 4, cliffDrop: 10 },
      lifts: [
        { type: 'chair', b: [0.5, 0.94], t: [0.44, 0.58], color: '#ff5400', name: 'Lavastrom' },
        { type: 'chair', b: [0.66, 0.66], t: [0.7, 0.28], color: '#ffbd00', name: 'Ascheweg', cost: 4 },
        { type: 'gondola', b: [0.36, 0.62], t: [0.42, 0.14], color: '#9d0208', name: 'Kraterbahn', cost: 8 },
        { type: 'tbar', b: [0.6, 0.3], t: [0.58, 0.12], color: '#e85d04', name: 'Fumarole', cost: 12 },
      ],
      pistes: [[0, 0], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [2, 1]],
      park: 0, paraglide: true, zip: 2,
      challenges: ['downhill', 'avalanche', 'slalom', 'collect', 'speed', 'airtime', 'race', 'bigair', 'freeride', 'giant', 'paraglide', 'superg', 'precision', 'freestyle', 'slopestyle', 'duel'],
    },
    {
      id: 'canyon', seed: 7707, W: 1152, L: 2048, unlock: 66,
      name: 'Rotfels-Canyon', region: { de: 'Utah · USA', en: 'Utah · USA' },
      desc: { de: 'Schnee auf rotem Sandstein, Tafelberge und glühende Sonnenuntergänge.', en: 'Snow on red sandstone, mesas and glowing sunsets.' },
      hour: 16.6, weather: 'clear', music: 'canyon', diff: 3,
      theme: { trees: { shrub: 2, pine: 2 }, pine: ['#3f5a3a', '#4b6a40', '#36503a'], rock: '#a4482e', rock2: '#c46a3f', treeDensity: 0.3, treeline: 0.3, rocks: 0.55, deco: 'canyon', tint: '#ff9f68', tintAmt: 0.12, snow: '#fbf6f2', palette: ['#ff7b3a', '#ffd1a1', '#a4482e'] },
      gen: { slopes: [0.5, 0.42, 0.36, 0.3, 0.24, 0.14, 0.04], big: 30, mid: 8, small: 0.8, ridge: 26, bowl: 26, cliffs: 6, cliffDrop: 13 },
      lifts: [
        { type: 'chair', b: [0.5, 0.94], t: [0.52, 0.56], color: '#ff7b3a', name: 'Mesa' },
        { type: 'chair', b: [0.28, 0.9], t: [0.24, 0.48], color: '#2a9d8f', name: 'Kojote' },
        { type: 'chair', b: [0.62, 0.6], t: [0.7, 0.16], color: '#264653', name: 'Bighorn', cost: 4 },
        { type: 'gondola', b: [0.4, 0.58], t: [0.38, 0.08], color: '#e9c46a', name: 'Sunset Tram', cost: 9 },
      ],
      pistes: [[0, 0], [0, 1], [1, 1], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 0, paraglide: true, zip: 2,
      challenges: ['airtime', 'slalom', 'collect', 'bigair', 'race', 'downhill', 'freeride', 'speed', 'freestyle', 'giant', 'paraglide', 'slopestyle', 'airtime', 'precision', 'superg', 'duel'],
    },
    {
      id: 'anden', seed: 8808, W: 1152, L: 2304, unlock: 84,
      name: 'Cerro Viento', region: { de: 'Patagonien · Anden', en: 'Patagonia · Andes' },
      desc: { de: 'Freeride-Paradies: steile Rinnen, Klippen und tiefer Pulver.', en: 'Freeride paradise: steep chutes, cliffs and deep powder.' },
      hour: 11, weather: 'cloudy', music: 'andes', diff: 3,
      theme: Object.assign({ rock: '#545a63', rock2: '#6c727c', treeDensity: 0.3, treeline: 0.55, rocks: 0.6, deco: 'alpine', palette: ['#4cc9f0', '#f72585', '#3a0ca3'] }, ALPINE),
      gen: { slopes: [0.8, 0.66, 0.52, 0.42, 0.32, 0.2, 0.05], big: 52, mid: 9, small: 1, ridge: 38, bowl: 22, cliffs: 7, cliffDrop: 13, deep: true },
      lifts: [
        { type: 'chair', b: [0.5, 0.94], t: [0.46, 0.58], color: '#4361ee', name: 'Cóndor' },
        { type: 'chair', b: [0.66, 0.62], t: [0.74, 0.22], color: '#f72585', name: 'Viento', cost: 4 },
        { type: 'tbar', b: [0.32, 0.6], t: [0.28, 0.28], color: '#4cc9f0', name: 'Guanaco', cost: 8 },
        { type: 'chair', b: [0.48, 0.32], t: [0.5, 0.06], color: '#3a0ca3', name: 'Cumbre', cost: 12 },
      ],
      pistes: [[0, 0], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 0, paraglide: true, zip: 1,
      challenges: ['freeride', 'airtime', 'avalanche', 'freeride', 'downhill', 'slalom', 'speed', 'collect', 'race', 'precision', 'bigair', 'paraglide', 'giant', 'airtime', 'superg', 'duel'],
    },
    {
      id: 'sturmhorn', seed: 9909, W: 1088, L: 2176, unlock: 104,
      name: 'Sturmhorn', region: { de: 'Hohe Tauern', en: 'High Tauern' },
      desc: { de: 'Nebel, Sturm und Lawinen: nur für Könner. Doppel-Diamant-Challenges!', en: 'Fog, storms and avalanches: experts only. Double-diamond challenges!' },
      hour: 13, weather: 'storm', music: 'storm', diff: 4,
      theme: Object.assign({ rock: '#4a4f57', rock2: '#5d636c', treeDensity: 0.38, treeline: 0.45, rocks: 0.55, deco: 'alpine', fog: 0.0026, palette: ['#adb5bd', '#e9ecef', '#343a40'] }, ALPINE),
      gen: { slopes: [0.85, 0.7, 0.55, 0.45, 0.34, 0.2, 0.05], big: 44, mid: 9, small: 1.1, ridge: 36, bowl: 24, cliffs: 6, cliffDrop: 12 },
      lifts: [
        { type: 'gondola', b: [0.5, 0.94], t: [0.5, 0.56], color: '#495057', name: 'Sturmbahn' },
        { type: 'chair', b: [0.3, 0.62], t: [0.26, 0.2], color: '#e63946', name: 'Blitz', cost: 4 },
        { type: 'chair', b: [0.68, 0.62], t: [0.72, 0.22], color: '#ffb703', name: 'Donner', cost: 8 },
        { type: 'tbar', b: [0.5, 0.3], t: [0.5, 0.07], color: '#219ebc', name: 'Gipfelschlepper', cost: 12 },
      ],
      pistes: [[0, 0], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2]],
      park: 0, paraglide: false, zip: 1,
      challenges: ['avalanche', 'fog', 'downhill', 'slalom', 'avalanche', 'speed', 'freeride', 'race', 'giant', 'collect', 'airtime', 'superg', 'bigair', 'freestyle', 'duel', 'treetap'],
    },
    {
      id: 'kristall', seed: 10110, W: 1024, L: 1920, unlock: 126,
      name: 'Kristalltal', region: { de: 'Verborgenes Tal', en: 'Hidden Valley' },
      desc: { de: 'Ein magisches Tal voller leuchtender Kristalle im ewigen Dämmerlicht.', en: 'A magical valley full of glowing crystals in eternal twilight.' },
      hour: 19.6, weather: 'clear', music: 'crystal', diff: 3, lamps: true,
      theme: { pine: ['#1f3b5a', '#26486b', '#2d557a'], trees: { spruce: 2, crystal: 2, pine: 1 }, rock: '#4b4e7a', rock2: '#6a5fa8', treeDensity: 0.42, treeline: 0.2, rocks: 0.4, deco: 'crystal', tint: '#8a6cff', tintAmt: 0.18, snow: '#f2f4ff', ice: '#9fb8ff', palette: ['#a98bff', '#7fe8ff', '#2a1b5c'] },
      gen: { slopes: [0.55, 0.46, 0.38, 0.32, 0.24, 0.13, 0.04], big: 38, mid: 8, small: 0.9, ridge: 24, bowl: 34, cliffs: 3, cliffDrop: 9, ice: 0.6 },
      lifts: [
        { type: 'gondola', b: [0.5, 0.94], t: [0.48, 0.54], color: '#7b2cbf', name: 'Amethyst' },
        { type: 'chair', b: [0.3, 0.6], t: [0.28, 0.14], color: '#00b4d8', name: 'Saphir', cost: 4 },
        { type: 'chair', b: [0.66, 0.6], t: [0.7, 0.16], color: '#ff4d6d', name: 'Rubin', cost: 8 },
        { type: 'tbar', b: [0.46, 0.92], t: [0.38, 0.7], color: '#ffd166', name: 'Topas' },
      ],
      pistes: [[0, 0], [0, 3], [3, 3], [1, 1], [1, 0], [2, 2], [2, 0], [2, 1]],
      park: 0, paraglide: true, zip: 2,
      challenges: ['collect', 'slalom', 'night', 'freestyle', 'race', 'bigair', 'collect', 'giant', 'paraglide', 'slopestyle', 'treetap', 'downhill', 'speed', 'freeride', 'superg', 'duel'],
    },
    {
      id: 'arena', seed: 11211, W: 1024, L: 1920, unlock: 150,
      name: 'Arena Weißkogel', region: { de: 'Wettkampfzentrum', en: 'Competition Venue' },
      desc: { de: 'Olympia-Feeling: Skisprungschanze, Big-Air-Kicker und Rennstrecken unter Flutlicht.', en: 'Olympic vibes: ski jump, big-air kickers and race tracks under floodlights.' },
      hour: 16, weather: 'clear', music: 'arena', diff: 3, lamps: true, skijump: true,
      theme: Object.assign({ rock: '#6e737b', treeDensity: 0.45, treeline: 0.2, rocks: 0.2, deco: 'arena', palette: ['#ff006e', '#3a86ff', '#ffbe0b'] }, ALPINE),
      gen: { slopes: [0.6, 0.48, 0.4, 0.34, 0.26, 0.14, 0.04], big: 30, mid: 6, small: 0.6, ridge: 14, bowl: 30, cliffs: 1, cliffDrop: 8 },
      lifts: [
        { type: 'chair', b: [0.42, 0.93], t: [0.4, 0.5], color: '#ff006e', name: 'Sprinter' },
        { type: 'chair', b: [0.64, 0.93], t: [0.68, 0.52], color: '#3a86ff', name: 'Schanzenlift' },
        { type: 'gondola', b: [0.4, 0.55], t: [0.42, 0.1], color: '#ffbe0b', name: 'Weltcup-Gondel', cost: 5 },
        { type: 'chair', b: [0.7, 0.56], t: [0.72, 0.14], color: '#8338ec', name: 'Abfahrtsbahn', cost: 9 },
      ],
      pistes: [[0, 0], [0, 1], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1]],
      park: 0, paraglide: false, zip: 1,
      challenges: ['skijump', 'bigair', 'slalom', 'giant', 'superg', 'downhill', 'race', 'slopestyle', 'skijump', 'speed', 'freestyle', 'collect', 'bigair', 'night', 'duel', 'skijump'],
    },
    {
      id: 'himmel', seed: 12312, W: 1216, L: 2560, unlock: 176,
      name: 'Himmelsleiter', region: { de: 'Himalaya', en: 'Himalaya' },
      desc: { de: 'Das Finale: die längsten Abfahrten der Welt, Gebetsfahnen und dünne Luft.', en: 'The finale: the world’s longest runs, prayer flags and thin air.' },
      hour: 9.6, weather: 'clear', music: 'himalaya', diff: 4,
      theme: Object.assign({ rock: '#5f5a57', rock2: '#7c746e', treeDensity: 0.3, treeline: 0.66, rocks: 0.55, deco: 'himalaya', palette: ['#ffd23f', '#2e6fd8', '#d62828'] }, ALPINE),
      gen: { slopes: [0.9, 0.72, 0.56, 0.44, 0.34, 0.22, 0.05], big: 56, mid: 9, small: 1, ridge: 44, bowl: 22, cliffs: 6, cliffDrop: 14, ice: 0.6 },
      lifts: [
        { type: 'gondola', b: [0.5, 0.95], t: [0.48, 0.66], color: '#d62828', name: 'Sherpa-Express' },
        { type: 'chair', b: [0.32, 0.7], t: [0.28, 0.36], color: '#2e6fd8', name: 'Yak', cost: 4 },
        { type: 'chair', b: [0.66, 0.7], t: [0.72, 0.34], color: '#2a9d4f', name: 'Schneeleopard', cost: 8 },
        { type: 'gondola', b: [0.5, 0.42], t: [0.5, 0.06], color: '#ffd23f', name: 'Himmelsbahn', cost: 12 },
      ],
      pistes: [[0, 0], [1, 1], [1, 0], [2, 2], [2, 0], [3, 3], [3, 1], [3, 2], [3, 0]],
      park: 0, paraglide: true, zip: 2,
      challenges: ['downhill', 'freeride', 'avalanche', 'paraglide', 'speed', 'slalom', 'airtime', 'race', 'superg', 'collect', 'precision', 'giant', 'bigair', 'freestyle', 'duel', 'downhill', 'avalanche'],
    },
  ];

  const PISTE_NAMES = {
    alpine: ['Panorama', 'Edelweiß', 'Gamsabfahrt', 'Sonnenhang', 'Talabfahrt', 'Adlerflug', 'Steinbock', 'Murmeltier', 'Almrausch', 'Enzian', 'Lärchenweg', 'Gipfelrunde'],
    nordic: ['Fjordblick', 'Rentierpfad', 'Polarlicht', 'Elchrunde', 'Mitternachtssonne', 'Trollstieg', 'Nordwand', 'Birkenweg', 'Wolfsspur'],
    japan: ['Sakura', 'Kitsune', 'Yuki', 'Kaminari', 'Tsuru', 'Momiji', 'Ryū', 'Hanabi', 'Kaze', 'Fuyu'],
    volcano: ['Lavafluss', 'Ascherinne', 'Magma', 'Schwefelweg', 'Obsidian', 'Kraterrand', 'Glut', 'Basalt', 'Feuerzunge'],
    canyon: ['Coyote Run', 'Mesa Drop', 'Red Ridge', 'Sandstone', 'Arches', 'Dust Devil', 'Sunset Line', 'Bighorn Bowl', 'Rattlesnake'],
    crystal: ['Amethyst', 'Saphir', 'Mondstein', 'Opal', 'Turmalin', 'Quarzweg', 'Prisma', 'Spiegeltal', 'Funkenflug'],
    arena: ['Weltcup', 'Olympia', 'Streif-Ost', 'Sprintstrecke', 'Zielhang', 'Super-G', 'Champions', 'Podium', 'Startschuss'],
    himalaya: ['Sherpa', 'Yeti-Pfad', 'Gebetsfahne', 'Annapurna', 'Schneeleopard', 'Himmelstor', 'Gletscherzunge', 'Mönchsweg', 'Lhotse-Rinne'],
  };
  PISTE_NAMES.volcano = PISTE_NAMES.volcano;

  GS.MOUNTAINS = MOUNTAINS;
  GS.PISTE_NAMES = PISTE_NAMES;
  GS.mountainById = (id) => MOUNTAINS.find((m) => m.id === id) || MOUNTAINS[0];
})(window.GS);
